### ISSUE TITLE
button not showing

### ISSUE THREAD

**Issue by opto** [xnotepp/xnote#1]
due to redesign of toolbars

**Comment by opto** [comment]
it is possible to permanently put it into mail-bar3. Maybe it/display it by pref

**Comment by froilo** [comment]
Button is shown again, but is not treated like all the other toolbar buttons. Labelling as "resolved" as the button is back again in a way that it could be release, but this requires more work - may be track that as another issue for the next release.

**Comment by froilo** [comment]
Closing this as the button shows up again, but created #36 for a final solution.
