### ISSUE TITLE
xNote window completely disappeared, reset does not work

### ISSUE THREAD

**Issue by pirx7** [xnotepp/xnote#105]
TB 91.13.1, xnote 3.3.2, win 10
xnote has been freshly installed.
It seems to be similar to the error _"Notes window disappears if moved too quickly. #20"_ 
But the workaround does not work.

On 2 out of 3 emails the notes window has now completely disappeared (probably due to **slow** moving) 
and cannot be restored by reset with
_"note's position can be reset to the default location using the context menu in the message list"_. 
So no editing is possible anymore. In the eMail itself the notes are still there.
Also a TB restart does not help.

Today after about 24h tried again, now I could reset one of the 2 corrupt xnotes.
The other one still remains gone. The difference was that it had a keyword.
But even after removing the keyword with the context menu the reset didn't work.

**Comment by pirx7** [comment]
I once played with the window movements.
Slow or fast doesn't matter.
They disappear rather randomly in nirvana.
If one goes into the Notes by editor, the following shows up:
     (The blanks here are displayed as "NUL" in the editor = 00 in hex).
A) 6209162**0**250 200 2022-11-20...  not visible (position moved with mouse, now nirvana)
B) 1878377 250 200 2022-11-20...  visible (position moved with mouse)
C) 1700250 250 200 2022-11-20...  visible (original position)

Obviously at A) the coordinates were shot and at least one "NUL" is lost.

**Comment by pirx7** [comment]
Changed with a real [hex editor HxD](https://mh-nexus.de/de/) as follows:
A) 1000250�250�200� 2022-11-20...
This makes the xNote window visible again.
So for absolute cases of emergency a way back.
But this can not be called a workaround.
At least the reset function must be fixed to be absolutely reliable.
Otherwise I can/will not use this nice AddOn.

**Comment by opto** [comment]
fast 'throwing' a note out of the visible screen, I can confirm that it cannot be reset, fortunately there is a red error in the error console, so a place to start debugging.

Klaus

**Comment by opto** [comment]
solved in next version
