### ISSUE TITLE
gRightMouseButtonSavedSelection is null - selection jumps back to previous mail when using the context menu

### ISSUE THREAD

**Issue by opto** [xnotepp/xnote#14]
something changed for context menus?

the variable still exists

**Comment by froilo** [comment]
Problem is that if one right clicks on a message and creates a note through the context menu, for example, the selection jumps back to the previously selected message so that one has no indication for which mail the note is actually created for.

**Comment by opto** [comment]
you mean if I create a note for a message that is not selected? I thought I fixed that by updating the selected variable (however it is called) upon mouseover. Maybe I need to add a select for the message at/after creating note.

**Comment by froilo** [comment]
Hi @opto, the issue is fixed according to what I understood should be the problem, but would be great if you do a final check whether you meant something else.
