### ISSUE TITLE
Please add a hotkey for adding notes 

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#15]
Issue moved from https://www.froihofer.net/bugzilla/show_bug.cgi?id=47

"Could you pls design a "hotkey" for adding the note more quickly? For example, when I want to add a note on a message, I can select the message and press "x(or other hotkeys)" to quickly add a note."

**Comment by opto** [comment]
keyboard operation has been added for TB 78. It is not a single key - but possible. So I would say workarounfd exists.

**Comment by opto** [comment]
keyboard action is now possible
