### ISSUE TITLE
Could you make the notes searchable?

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#16]
Moved from https://www.froihofer.net/bugzilla/show_bug.cgi?id=50

In principle, this would be possible, although currently not practicable – anyone willing to contribute this? 

If you are in urgent need for this, open your Thunderbird profile directory (http://kb.mozillazine.org/Profile_folder_-_Thunderbird), look for the folder called "XNote" and use a simple file search to look for the file containing the text.The notes can be viewed in a text editor (see question below). If you want to see the corresponding message, use the Thunderbird e-mail search to search, select "Customize..." to add a "Message-ID" header and search within this field for the message ID – the file name of the note without the ".xnote" extension.

**Comment by opto** [comment]
in v3.5.9
