### ISSUE TITLE
The notes window is not shown if the preview message pane (F8) is disabled.

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#24]
Moved from https://www.froihofer.net/bugzilla/show_bug.cgi?id=60

**Comment by opto** [comment]
that is understandable because the note display is tied to a function checking the mail subject in the message display.
If no message display, there can't be a note display.
This needs to be changed.

**Comment by opto** [comment]
maybe tie display of note to click in threadpane instead

**Comment by opto** [comment]
solved? may need more testing. not yet in master

**Comment by opto** [comment]
lost or not committed to master? In any case, not working in 78.10,1.
Need to look at my commits on Oct. 30th 2020

**Comment by opto** [comment]
correct, that is in ESR78-cleanup branch, not in master
