### ISSUE TITLE
First x characters not shown in XNote column

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#31]
In the current state of the updates for TB78, the first x characters are not shown in the XNote column. The issue is that the `getCellText` function is never called while `getImageSrc` is still called. Therefore, the icon is shown while there is no text. This would indicate that it might as well be a Thunderbird bug - at least some changed behaviour for TB78 that needs to be sorted out.

**Comment by froilo** [comment]
Has either to be fixed for the next release or documented as not working.

**Comment by opto** [comment]
that was working in 78.3 on Win 10 home. It might be caused by the column text width being set to 0 in the settings? Or it is a regression after fixing something else? I will doublecheck.

**Comment by opto** [comment]
seems to be caused by 78.4? was working in 78.3.x

**Comment by opto** [comment]
forgot to remove cycler from column
