### ISSUE TITLE
Integrate toolbar button as a regular button that can be added, moved, and removed

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#36]
In the port to TB78, the solution to show the toolbar button is not a final solution as it adds the button hard-coded, not fully integrated into the toolbar mechanism. This should be changed so that it becomes a button like all the others again.

**Comment by Cryo99** [comment]
When can we expect to see this? It's nice that it's fixed. I came here to report the same bug. 🥳

**Comment by froilo** [comment]
> When can we expect to see this? It's nice that it's fixed. I came here to report the same bug. 🥳

Will probably create the next release within a week.
