### ISSUE TITLE
Add-on installation requires TB restart in order to get the XNote++ column working

### ISSUE THREAD

**Issue by froilo** [xnotepp/xnote#39]
This has become an issue with TB 78 as earlier TB had to be restarted anyway to get XNote++ working, but now triggers the installation right away.

**Comment by opto** [comment]
??
on temp install, the column needs to be activated in a folder
somewhere, one can apply this to all folders
after activating the column, one needs to change folder and back to display the icons.
I think no restart needed, but not showing the icons directly is definitely a bug.
I once saw an invalidate for rows somewhere, that may be what we need

**Comment by opto** [comment]
workaround: no restart is needed, but one needs to click in another folder.
When going back to the original folder, the column works

**Comment by opto** [comment]
fixed in 102
