### ISSUE TITLE
XNote++ 3.1.0 incompatible with ImportExportTools NG version 10.0.2

### ISSUE THREAD

**Issue by pmruzicka** [xnotepp/xnote#48]
I guess XNote updated, but I am clueless as to where the icon went, and there is no longer a way to add a note. In fact, all the previous notes that I had added are no longer showing up. I don't even know where to start looking to see what might be going on. All I know is that it is installed and acting as if it is NOT installed.

**Comment by froilo** [comment]
If the icon is not visible, please try to add it again through the toolbar customization - right click on the tool bar and select "Customize..." (or something like that - it should be the only entry with "..." at the end).

There is a issue with preference migration for the storage location if you changed it - see #47 for further details and a workaround for it.

**Comment by pmruzicka** [comment]
I changed nothing. Used it as it was normally installed (previous and old version). I just now removed the new version and installed the previous version and it now works again. I have also stopped updates from happening automatically so it does not update to the new version again. I don't have the time to screw around with it.

**Comment by pmruzicka** [comment]
As a side note - I saw 3.1.1 released and I installed it. Same thing happened. I have no access to XNote at all. I removed 3.1.1 and reinstalled 3.0.0 and Xnote functions properly again. So apparently it has nothing to do with what was fixed.

**Comment by froilo** [comment]
Please tell me:
* your operating system and version
* your Thunderbird version
* whether you are using the default storage location and if not, whether you have tried to change the storage location after installing 3.1.1. This should bring back your notes in case you used a custom location earlier.
* whether you tried to add the toolbar button through the customization of the toolbar. The button is automatically added if XNote is installed for the first time. If it was installed earlier, it is not added again in order not to annoy people with the toolbar button being shown again after each update in case they removed it.

If the XNote column is not visible, it has to be manually added through the column picker.

Please restart Thunderbird after you installed a new version. It seems there are still some topics that are resolved after a restart, e.g., not working XNote column until restart after XNote installation.

**Comment by pmruzicka** [comment]
It is not just the toolbar button. I can't even use the drop down on an email to add an XNote. Column picker has no evidence of XNote (which it does when I reinstall the old version). NOTHING is there anywhere. It is like the whole thing disappears. The button is NOT in the customization menu.

OS is Windows 10 Build 1909 (18363.1237)
Thunderbird 78.5.1
I have never changed the storage location as I didn't even know it existed.

I did restart Thunderbird after restart. It did not change anything.

**Comment by pmruzicka** [comment]
Oops, sorry. Mistake above. The button is in the Customization menu, and I can add it, but is is grayed out and will not function.

Drop down I am referring to is a right click on an email, which gave the ability to add Xnote to email.

**Comment by opto** [comment]
we need to add the removeEventHandlers. That is no longer automatic. I just tested in a testcase: if we do that, restart is not necessary on many situations. I will revive that from the leftout branch.

**Comment by froilo** [comment]
Hello @pmruzicka, could you please post the content of the error console right after a Thunderbird restart? You can get that content through menu - Tools - Developer tools - Error console (in my locale it has the shortcut Ctrl+Shift+J).

Side note - was on TB 78.5.0 - upgraded - XNote++ still working for me.

**Comment by pmruzicka** [comment]
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
Successfully loaded OpenPGP library rnp.dll from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:49:13
Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
1606952810466	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:570:20) JS Stack trace: readJSON/</<@Extension.jsm:570:20
onStopRequest@NetUtil.jsm:128:18
moz-extension://1e08ebc7-0735-4b47-9ecb-7b66ffbf267e/ phoenityButtons.js:2:9
public keys: 0, secret keys: 0 RNPLib.jsm:247:15
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
WebExtensions: STARTUP qf-startup.js:1
Object { Preferences: {…} }
xn-background.js:112:13
WebExtensions: 
Object { XnotePrefs: {…} }
xnote-experiments.js:97
New XNote Prefs: {"usetag":false,"dateformat":"yyyy-mm-dd - HH:MM","width":250,"height":200,"horPos":1020,"vertPos":460,"show_on_select":true,"show_first_x_chars_in_col":20,"storage_path":"[ProfD]XNote","migratedLegacy":1} commons.jsm:73:15
checkXNoteTag: usetag=false commons.jsm:83:15
xnote: storageDir initialized to: C:\Users\PaulM\AppData\Roaming\Thunderbird\Profiles\z165jkid.default\XNote storage.jsm:47:15
WebExtensions: storedVersion: 3.1.1; comparison: false xnote-experiments.js:73
checkXNoteTag: usetag=false commons.jsm:83:15
xnote: storageDir initialized to: C:\Users\PaulM\AppData\Roaming\Thunderbird\Profiles\z165jkid.default\XNote storage.jsm:47:15
Refresh tag cache in categories. background.js:304:11
Refreshed. background.js:338:13
1606952812191	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing background.scripts: An unexpected property was found in the WebExtension manifest.
1606952812194	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing theme_icons: An unexpected property was found in the WebExtension manifest.
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
WebExtensions: prefsButton added phoenityButtonsApi.js:26
WebExtensions: devToolsButton added phoenityButtonsApi.js:45
WebExtensions: configButton added phoenityButtonsApi.js:64
WebExtensions: restartButton added phoenityButtonsApi.js:83
WebExtensions: searchButton added phoenityButtonsApi.js:101
WebExtensions: 78.5.1 qFi-messenger.js:11
quickFilters [logTime init]
Util.VersionProxy() started.
quickFilters 18:46:53.33  [0 ms]   
AddonManager.getAddonByID .. added callback for setting extensionVer.
quickFilters 18:46:53.33  [0 ms]   
toggleCurrentFolderButtons()
QF-prefs quickfolders-preferences.js:11:9
WebExtensions: 78.5.1 qf-messenger.js:24
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://xnote/content/xnote-classe.js :: <TOP_LEVEL> :: line 11"  data: no] xnote-classe.js:11:27
quickFilters 18:46:53.99  [66 ms]   
AddonManager: quickFilters extension's version is 5.0.2
Successfully loaded OTR library libotr-5.dll from C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:43:13
As Facebook deprecated its XMPP gateway, it is currently not possible to connect to Facebook Chat. See bug 1141674. facebook.jsm:25
quickFilters 18:46:55.375  [2276 ms]   
=================quickFilters==============
   checkFirstRun() - attempt 1
quickFilters 18:46:55.375  [0 ms]   
firstRun = false  - currentVersion = 5.0.2  - installed = 5.0.2
quickFilters 18:46:55.375  [0 ms]   
store installedVersion: 5.0.2
QuickFolders [logTime init]
Error in addFolderButton: folder parameter is empty!
Entry: League10
QuickFolders 18:46:55.994  [27 ms]	 
Error in addFolderButton: folder parameter is empty!
Entry: cosolargy.net
QuickFolders 18:46:56.146  [152 ms]	 
Error in addFolderButton: folder parameter is empty!
Entry: League10
QuickFolders 18:46:56.169  [23 ms]	 
Error in addFolderButton: folder parameter is empty!
Entry: cosolargy.net
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. www.google.com
Lightning: [calCachedCalendar] replay action failed: <unknown>, uri=googleapi://firexross@gmail.com/?calendar=%23contacts%40group.v.calendar.google.com, result=[object Object], operation=[object Object] calCachedCalendar.js:346
quickFilters 18:48:46.180  [110805 ms]   
validateLicense(QI-firexross@gmail.com:2021-05-01;0169acca29371b18ca49ef31731fbcd093c9706bbae4f15f7a0dc61182c0e551 017c97a0847912797864e521185d06f7af67959a6e58125478f75abe22b4f31d)
quickFilters 18:48:46.181  [1 ms]   
RSA.initialise(35)
quickFilters 18:48:46.181  [0 ms]   
Creating RSA key + decrypting
quickFilters 18:48:46.181  [0 ms]   
new RSA.RSAKeyPair()
quickFilters 18:48:46.183  [2 ms]   
get RSA.decryptedString()
quickFilters 18:48:46.197  [14 ms]   
Decryption Complete : decrypted string = QI-firexross@gmail.com:2021-05-01
quickFilters 18:48:46.198  [1 ms]   
validateLicense() - successful.
quickFilters 18:48:46.198  [0 ms]   
validateLicense()
 returns Valid   [1]

​

**Comment by hebu** [comment]
Same problem here.

- Thunderbird 78.5.1 64-bit
- XNote++ 3.1.1

When the XNote++ add-on came back to my mail client its button was to the far right and unmovable, but everything was working.

Now the button to the far right disappeared and all XNote columns disappeared and there's also no entry in the context menu to add a note. Notes are also not visible. I can move the XNote button back in to the symbols menu, but it is greyed out.

**Error console right after program start, filtered for "xnote":**

```
New XNote Prefs: {"usetag":false,"dateformat":"yyyy-mm-dd - HH:MM","width":250,"height":200,"horPos":250,"vertPos":200,"show_on_select":true,"show_first_x_chars_in_col":20,"storage_path":"[ProfD]XNote","migratedLegacy":1} commons.jsm:73:15
checkXNoteTag: usetag=false commons.jsm:83:15
WebExtensions: 
{…}
​
XnotePrefs: Object { usetag: false, dateformat: "yyyy-mm-dd - HH:MM", width: 250, … }
​
<prototype>: Object { … }
xnote-experiments.js:97
xnote: storageDir initialized to: D:\DATEN\TBIRD\Profiles\hebu\XNote storage.jsm:47:15
checkXNoteTag: usetag=false commons.jsm:83:15
WebExtensions: storedVersion: 3.1.1; comparison: false xnote-experiments.js:73
xnote: storageDir initialized to: D:\DATEN\TBIRD\Profiles\hebu\XNote storage.jsm:47:15
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://xnote/content/xnote-classe.js :: <TOP_LEVEL> :: line 11"  data: no] xnote-classe.js:11:27
    <anonym> chrome://xnote/content/xnote-classe.js:11
    <anonym> jar:file:///D:/DATEN/TBIRD/Profiles/hebu/extensions/xnote@froihofer.net.xpi!/chrome/content/scripts/xn-xnote-overlay.js:3
    _loadIntoWindow jar:file:///D:/DATEN/TBIRD/Profiles/hebu/extensions/xnote@froihofer.net.xpi!/experiment-apis/WindowListener/windowlistener.js:409
    onLoadWindow jar:file:///D:/DATEN/TBIRD/Profiles/hebu/extensions/xnote@froihofer.net.xpi!/experiment-apis/WindowListener/windowlistener.js:307
    checkAndRunExtensionCode resource:///modules/ExtensionSupport.jsm:220
    _checkAndRunMatchingExtensions resource:///modules/ExtensionSupport.jsm:195
    _addToListAndNotify resource:///modules/ExtensionSupport.jsm:179
    _waitForLoad resource:///modules/ExtensionSupport.jsm:156
Gewechselt zu chrome://messenger/content/messenger.xhtml
```

**Comment by froilo** [comment]
Received the information that XNote++ now at least collides with ImportExportTools NG version 10.0.2. If that is the root cause, I don't know why XNote 3.1. would be any different to 3.0.

What happens, if you deactivate your other add-ons. Does XNote++ work in that case?

This topic raises the suspicion that there might be some namespace collisions. Renamed some stuff to check. If you are facing the "not working" issue, could you please try the following version: https://www.froihofer.net/temp/xnote-3.1.2a.xpi (may be you have to right click and "save target as ..."; install it through the add-ons manager from the local file system).

**Comment by pmruzicka** [comment]
I disabled ImportExportTools NG version 10.0.2 and XNote++ 3.1.1 started working again. Do you still want me to try the 3.1.2 and reenable  ImportExportTools NG version 10.0.2??????

**Comment by froilo** [comment]
Not necessary, due to the information about ImportExportTools NG, I can reproduce the issue meanwhile and it's not fixed.

**Comment by hebu** [comment]
I also had ImportExportTools NG installed and now - after deactivating it - XNote++ is functionable again.

So that's a temporary workaround for me as I do not use ImportExportTools regularly - thanks for helping! :)

**Comment by opto** [comment]
at my end, installing both as temporary addons, they live happily next to each other. I see that Christopher uses a very old version of Windowlistener and will email him about that. I had some problems with WL 1.20. Next, will try with xpi's.
I used top of master, does that solve the problem already? Also, if classes not renamed, maybe TB cannot live with one having WL 1.20, the other having WL1.27 (or whatever we have). Although, in theory, John loads them into addon specific namespaces.

**Comment by opto** [comment]
just noticed that the new version of WL is still sleeping in the uncommitted branch, and we are totally old at WL 1.14. I will try what happens if we update both 3.1.0 (before rename) and Christphers addon to newest WL

**Comment by opto** [comment]
if anybody is willing to test these two new addon versions: it is xnote 3.1.1 with newest WL and importExport... with newest WL.

Here, they seem to work next to each other. Column is there, button as well, context menu working.

Only problem I see is that the icon in the column sometimes is delayed or shown anly after switching folder away and back, but I think w had that before.
On my side, I first installed xnote, tested it, then importexporttolls, the tested xnote again. Using 78.5.1
[importexporttools_ng-10.0.2-tbnewWL.zip](https://github.com/xnotepp/xnote/files/5645969/importexporttools_ng-10.0.2-tbnewWL.zip)
[xnote3.1.1newWL.zip](https://github.com/xnotepp/xnote/files/5645970/xnote3.1.1newWL.zip)

I cannot upload the files with extension xpi, the post only accepts zip. xpi == zip. You can rename but do not need to, TB accepts both.
Hope that helps.

Klaus

**Comment by opto** [comment]
no it does not help. The problem only comes up after the next TB start. Works fine while both are installed, until we end and restart TB. Then, it cannot find the xnote.jsm file (= TB problem? Will ask John tomorrow)
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://xnote/content/xnote-classe.js :: <TOP_LEVEL> :: line 11"  data: no]

line 11, we load the xnote.jsm :var {xnote} = ChromeUtils.import(extension.rootURI.resolve("chrome/modules/xnote.jsm"));
meaning TB loads it but cannot find it, if importexporttolls is present.

**Comment by opto** [comment]
another observation:  the  problem comes up if xnote is installed as second of the two. That happens also for temp install if second.

**Comment by opto** [comment]
this is the problem:  (in xnote-classe)
if (!extension) var extension = ExtensionParent.GlobalManager.getExtension("xnote@froihofer.net");

extension is already defined in importexporttools and visible here, so it does not load our extension

Do we need a workaround? I am sure John will solve that on Monday. Otherwise, we could rename the variable.

**Comment by opto** [comment]
temporarily works without the if (!extension) , but not fully tested (but error message gone and column again in column picker

**Comment by opto** [comment]
we need to replace extension by xnote.ns.extension

**Comment by cleidigh** [comment]
@opto 
all
I have a temporary fix for import export toolsNG for anyone who wants it:
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.3/xpi/import-export-tools-ng-10.0.3-b1-tb.xpi
@cleidigh

**Comment by froilo** [comment]
Version 3.1.2 containing this fix has already been approved by the add-ons review team. Would be great if anyone who faced that issue updates to 3.1.2, verifies things are working, and closes this issue to confirm the fix.

**Comment by froilo** [comment]
It seems I've been a bit too quick with the fix - it works using the context menu, but the toolbar is broken. This is fixed meanwhile - and already received a confirmation. Will send the fix on its way.
