### ISSUE TITLE
XML Parsing Error: undefined entity

### ISSUE THREAD

**Issue by WuaznBoanige** [xnotepp/xnote#56]
XML Parsing Error: undefined entity
Location: chrome://xnote/content/xnote-window.xhtml
Line Number 50, Column 4:

with Xnote 3.1.4 beta a on TB 78.9.0 (64-bit)
![XNote Parser Error](https://user-images.githubusercontent.com/81583584/112876577-f8ad5c00-90c5-11eb-8441-0282ff45bdb7.JPG)

**Comment by opto** [comment]
I will test, but I don't think this version is supposed to work below TB 86. Once again, there is a irreversible change at TB 86 as compared to TB 78-85.
In the neantime, there are new features: print note, forward note by email. Over Easter or shortly after, I will make this a new version for TB 78.

Klaus

**Comment by opto** [comment]
just doublechecked: still working in 87. Most likely, those changes are not backward compatible to 78

**Comment by WuaznBoanige** [comment]
Hi Klaus.

Thanks for quick response and clarification. I appreciate your app really. Great work!

Greetings from Berlin und schöne Ostern. :)

Andreas

⁣Get BlueMail for Android ​

**Comment by opto** [comment]
this is working in 78.10.1 64 bit. I am preparing a new version for ATN, will need a few days. Maybe I will repackage my code, because I am using 'temporary addon loading'.

Klaus

**Comment by opto** [comment]
a translation string was missing
