### ISSUE TITLE
Cannot add new note (xnote3.1.4beta.a.xpi)

### ISSUE THREAD

**Issue by szelenyit** [xnotepp/xnote#58]
Hi!
Cannot add new note with the new test version (xnote3.1.4beta.a.xpi)
TB 78.10.0 (32-bit)

See below:

```
XML Parsing Error: undefined entity
Location: chrome://xnote/content/xnote-window.xhtml
Line Number 50, Column 4:
			<image
------------------------^
```

![bug-xnote](https://user-images.githubusercontent.com/83358722/116788830-1a767600-aaac-11eb-86b0-3d9d26be805b.JPG)

**Comment by opto** [comment]
thanks, I will have a look at it next week.

Klaus

**Comment by opto** [comment]
see #56. It seems this TB 86 fix is not backward compatible for 78. Please use previous version of xnote until I update.

Klaus

**Comment by opto** [comment]
I just tested on TB 78.10.1 64 bit Win 10. Using the button, I can create a new xnote.

Can you give more info? Which OS, how did you ceate the note?

Klaus

**Comment by zevrix** [comment]
I have exactly the same problem with 3.1.4 beta. Exactly the same error message.

macOS 11.2
TB 78.10.1

The problem affects all notes: can't create new notes; can't read full text of existing notes (the text in the column is ok).
Both button and contextual menu give same results.

I reverted to the stable 3.1.3 (which means the "column width after relaunch" bug is back.

**Comment by opto** [comment]
I am just now working on the new version. (for 78.10).
If you look at error console, is there any message relevant to xnote?
Error console (on PC) opens with ctrl-shift-j, all pressed at the same time. Not sure whether some other key replaces ctrl on a MAC.

**Comment by zevrix** [comment]
> If you look at error console, is there any message relevant to xnote?

In Console I only see the same error as the one displayed by XNote itself:

```
 XML Parsing Error: undefined entity
Location: chrome://xnote/content/xnote-window.xhtml
Line Number 50, Column 4:
```
There are some other messages from XNote but they're not errors.

XNote displays the same window as in the screenshot by the original poster:

```
XML Parsing Error: undefined entity
Location: chrome://xnote/content/xnote-window.xhtml
Line Number 50, Column 4:

			<image
------------------------^
```

**Comment by opto** [comment]
we found that this a a language problem. For english, a translation was missing

**Comment by zevrix** [comment]
Thanks!

Just to make sure: are you going to update the current beta with this fix sometime soon?

**Comment by opto** [comment]
it is uploaded and in review. Number 1 of 3. so hopefulls soon comes as an update.  Klaus

>
