### ISSUE TITLE
Xnote stopped working with TB 91.3.1

### ISSUE THREAD

**Issue by piMyHome** [xnotepp/xnote#75]
After updating to TB 91.3.1 I get this error when creating or opening a note:

XML Parsing Error: no root element found
Location: chrome://xnote/content/xnote-window.xhtml
Line Number 1, Column 1:

**Comment by McGerbick** [comment]
I am encountering a similar problem, however the error pops up when coming back to a message with an XNote. I still can create an XNote message and later can read it in the yellow area below the e-mail header.

**Comment by McGerbick** [comment]
Have you seen issue #72? The problem seems to be resolved with XNote version 3.2.8.

**Comment by piMyHome** [comment]
Thanks a lot, this did the trick...
