### ISSUE TITLE
TB crashes after sorting messages by xnotes

### ISSUE THREAD

**Issue by pikOuAl** [xnotepp/xnote#82]
TB crashes every time it starts. But if I uninstall xnote++ everything works. Even if I reinstall xnote everything works fine until I change the file path to any folder on our server. Then TB crashes again.

Before this problem started we wanted to sort the messages by xnotes, after that this problem started.

**Comment by opto** [comment]
what happens if you just change the folder path to a local directory? Does that work?

If yes, then discovering the server fails?

**Comment by pikOuAl** [comment]
I had now changed it to a local directory and it's working again. After I changed it back to the server path, everything suddenly works again. I haven't changed anything else.
