### ISSUE TITLE
Constant freezes under TB91

### ISSUE THREAD

**Issue by Feri-6** [xnotepp/xnote#83]
TB occasionally (every few minutes) freezes for a short time, 1-2 seconds. If I turn X-Note off, the freezes will stop. I experienced it on multiple computers.
TB 91.5.1.
Xnote 3.2.10

**Comment by MartinX3** [comment]
Do you use the conversations plugin, too?
I see a performance degradation with it, which also slows down the notes rendering.

**Comment by Feri-6** [comment]
No, I do not use it. But it seems that something else is causing the problem, I just don't know what. If I start in safe mode, everything is fine, but if I start in normal mode with disabled plug-ins, TB freezes.

**Comment by MartinX3** [comment]
Is there anything listed in the thunderbird activities window after you cleaned the finished tasks in the list?

**Comment by opto** [comment]
which OS?

**Comment by Feri-6** [comment]
Maybe it caused by Nostalgy++ plug-in, not Xnote.
