### ISSUE TITLE
SOS!! XNote 3.2.10 doesn't work with TB 101.0 (Mac)

### ISSUE THREAD

**Issue by zevrix** [xnotepp/xnote#90]
XNote  3.2.10 stopped working after updating to TB 101.0b1 (at least on Mac).

`extensions.checkCompatibility.101.0` is set to` false`

_XNote++_ button does appear in the toolbar. But that's it: nothing else related to XNote is available. Can't enable the column, create/modify notes etc.

Thanks again for your efforts!

P.S. XNote did work with TB 100. I just had to restore my Profiles folder from TB 100 and revert back to TB 100. Now XNote works again.

**Comment by jobisoft** [comment]
I updated the add-on for 102 in PR #95 . If you have the time, testing it will help to detect issues:
[xnote_3.3.zip](https://github.com/xnotepp/xnote/files/8968603/xnote_3.3.zip)
s

**Comment by jobisoft** [comment]
Can you add a screenshot how it is and how it should be?

**Comment by jobisoft** [comment]
Does that fix it?
[xnote_3.3.1.zip](https://github.com/xnotepp/xnote/files/8970129/xnote_3.3.1.zip)

**Comment by zevrix** [comment]
Yes it does fix it - perfect!

XNote works as expected and is compatible with 102.

Thanks for addressing my bug report on Bugzilla so quickly. Greatly appreciated.

(P.S. One minor longstanding bug still remains in XNote - I'll submit it here separately soon).

**Comment by jobisoft** [comment]
@zevrix : Could you test if v3.3.1 also works in TB91, so it can be released as backward compatible, or do we have to limit it to 102+ ?

Thanks for your help,
John

**Comment by zevrix** [comment]
@jobisoft:

I just tested v3.3.1 with TB 91 - all works as expected.

Also, this last bug #96 does not happen in TB 91 - but does happen in TB 102 (and few versions back).
