### ISSUE TITLE
Upgrading Thunderbird to version 102.2.2 and Xnote++ is not working anymore

### ISSUE THREAD

**Issue by spechto** [xnotepp/xnote#98]
Xnote++ version is 3.3.2, but there is no xnote column displayed. Also there is no xnote colum in the column selector.
I tried to remove the AddOn and reinstall it, but the same effect.

**Comment by opto** [comment]
is there  any message in the error console (ctrl-shift-j, all at the same time)?
Which TB version, OS?

best would be: deinstall XNote. Shutdown, restart TB (all TB windows must be closed)
Open error console, empty it by click on trash icon
install XNote, the look at error console.

**Comment by spechto** [comment]
Hello together, 

after the Error Console did not provide any useful feedback, I have completely reinstalled Thunderbird with completely new profiles - without solving the problem :-(
Because I am using abolute pathes for my profile, which has worked a lot of years without problems, I tried a lot other things before, but at last, the solution was still simple. In the profiles.ini I had to correct the absolute path:

Path:=D:\\\\MyMail\\\\Thunderbird\\\\Profiles\\\\xyzwhatever.default

had to be changes to

Path:=D:\MyMail\Thunderbird\Profiles\xyzwhatever.default

I think that in very old versions of Thunderbird the double "\\" was necessary, and since the 10X-version it causes problems in some addons. 

Thanks and best Regards
Martin
